[package]
name = "nano-risc"
version = "0.1.0"
edition = "2021"

[dependencies]
parser = { package = "parser", path = "../parser" }
vm ={ package = "vm", path = "../vm" }
clap = { version = "4.4.6", features = ["derive"]}
